## Caching the Inverse of a Matrix:
## Matrix inversion is usually difficult and time consuming to compute repeatedly. 
## Thus, there are benefits to caching the inverse of a matrix.
## Below are functions that are used to generate an object that 
## stores a matrix and caches its inverse.

## This function creates a "matrix" object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) inv <<- inverse
  getInverse <- function() inv
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}




## This function computes the inverse of the "matrix" generated by abov
## makeCacheMatrix. If the inverse has already been calculated (and the 
## matrix has not changed), then it should get the inverse from the cache.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inv <- x$getInverse()
  if (!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  mat <- x$get()
  inv <- solve(mat, ...)
  x$setInverse(inv)
  inv
}
